// <auto-generated />
using System;
using Infrastructure.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(AdminApplicationDbContext))]
    [Migration("20230528182258_UpdateSeeds")]
    partial class UpdateSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admins.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e54f0cd-21d9-406d-bf67-e3bce0ce1199"),
                            FirstName = "Админ",
                            LastName = "Админов",
                            Login = "admin",
                            MiddleName = "Админович",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Albums.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            IsActive = false,
                            Name = "17",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            IsActive = false,
                            Name = "Whole Lotta Red",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            IsActive = false,
                            Name = "RED & WHITE",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            IsActive = false,
                            Name = "Life Of Pi'erre 5",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e4b2c83d-384f-4d68-bbd0-ef8fdd9e9d25"),
                            Code = 0,
                            IsActive = false,
                            Name = "Divide",
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5711de71-8cb5-4be9-984f-d1683760a9a6"),
                            Code = 0,
                            IsActive = false,
                            Name = "Sweetener",
                            ReleaseDate = new DateTime(2018, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            IsActive = false,
                            Name = "Scorpion",
                            ReleaseDate = new DateTime(2018, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("73c8af54-d09b-4ef7-b646-901e59b868ed"),
                            Code = 0,
                            IsActive = false,
                            Name = "1989",
                            ReleaseDate = new DateTime(2014, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cc37dd0a-7831-4b4b-babb-259b4d06598d"),
                            Code = 0,
                            IsActive = false,
                            Name = "24K Magic",
                            ReleaseDate = new DateTime(2016, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d9d9d08b-5422-4458-a4de-34ac03a5f52e"),
                            Code = 0,
                            IsActive = false,
                            Name = "Anti",
                            ReleaseDate = new DateTime(2016, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("89901ee5-7d1f-48a4-8e92-83a9b5c76f1e"),
                            Code = 0,
                            IsActive = false,
                            Name = "DAMN.",
                            ReleaseDate = new DateTime(2017, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c3e23e47-c858-4c1c-9000-bd3f4e8fb1f0"),
                            Code = 0,
                            IsActive = false,
                            Name = "When We All Fall Asleep, Where Do We Go?",
                            ReleaseDate = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8b9dcb0b-2f8d-4f0c-8645-0e8d588a4f5e"),
                            Code = 0,
                            IsActive = false,
                            Name = "Purpose",
                            ReleaseDate = new DateTime(2015, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Albums.AlbumGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("AlbumGenres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("262342b2-861e-4802-a54c-c84522188cd7"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            GenreId = new Guid("ae14797c-31cd-432a-b2de-b3db95a82ab4")
                        },
                        new
                        {
                            Id = new Guid("395d511c-4387-46e8-9868-f8be6ea5c517"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            GenreId = new Guid("8745e56f-b335-43fe-bd10-bad6bead0892")
                        },
                        new
                        {
                            Id = new Guid("444757cc-64ec-46b3-a97b-6c31e25d7d18"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            GenreId = new Guid("2f044c88-a983-4cf5-bcc1-a5d7764507ed")
                        },
                        new
                        {
                            Id = new Guid("46e8fe85-9e9d-4ab1-b711-2a100f9402c6"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            GenreId = new Guid("8745e56f-b335-43fe-bd10-bad6bead0892")
                        },
                        new
                        {
                            Id = new Guid("49318a5d-3a15-4ca5-8a26-71c5e0928bee"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            GenreId = new Guid("baa56e06-9672-4118-aee3-4098cec4581e")
                        },
                        new
                        {
                            Id = new Guid("631bc28a-fc2c-406e-9bd6-3dcd90ef2bf4"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            GenreId = new Guid("e2a8929f-2190-4329-bae1-83b170a3677f")
                        },
                        new
                        {
                            Id = new Guid("9788b398-eb7d-4f0a-a778-a595edf8764e"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            GenreId = new Guid("ae14797c-31cd-432a-b2de-b3db95a82ab4")
                        },
                        new
                        {
                            Id = new Guid("c2d56b4f-1968-42e0-b95c-ceb4cd976ffd"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            GenreId = new Guid("8745e56f-b335-43fe-bd10-bad6bead0892")
                        },
                        new
                        {
                            Id = new Guid("f1279fe9-84d4-417e-8b5b-627e0b4e6029"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            GenreId = new Guid("8745e56f-b335-43fe-bd10-bad6bead0892")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Artists.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            Code = 0,
                            Email = "xxxtentacion@gmail.com",
                            IsActive = false,
                            Name = "XXXtentacion",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            Code = 0,
                            Email = "playboi@gmail.com",
                            IsActive = false,
                            Name = "Playboi Carti",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("c9c8d64c-fa56-4e2e-b8ef-6e41d00735e1"),
                            Code = 0,
                            Email = "liluzivert@gmail.com",
                            IsActive = false,
                            Name = "Lil Uzi Vert",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("90ac1df8-837d-42af-a40a-a0cbd28770fd"),
                            Code = 0,
                            Email = "bourne@gmail.com",
                            IsActive = false,
                            Name = "Pi'erre Bourne",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("c90e2e7e-15d1-4a7c-8a8e-9f28e7f0c36f"),
                            Code = 0,
                            Email = "beyonce@gmail.com",
                            IsActive = false,
                            Name = "Beyoncé",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("d8956234-3e1b-4c14-ae78-9b7f1f598ef2"),
                            Code = 0,
                            Email = "edsheeran@gmail.com",
                            IsActive = false,
                            Name = "Ed Sheeran",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("f024e3f8-cf68-4c48-b288-b04e9c8b30c2"),
                            Code = 0,
                            Email = "arianagrande@gmail.com",
                            IsActive = false,
                            Name = "Ariana Grande",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("a7ab352a-421d-4f78-9a5c-72d2cfa9c430"),
                            Code = 0,
                            Email = "drake@gmail.com",
                            IsActive = false,
                            Name = "Drake",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("87f352c1-ef43-41fb-b5c1-3a46e51868b8"),
                            Code = 0,
                            Email = "taylorswift@gmail.com",
                            IsActive = false,
                            Name = "Taylor Swift",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("640e13de-bd1e-4088-8651-44be51f2451d"),
                            Code = 0,
                            Email = "brunomars@gmail.com",
                            IsActive = false,
                            Name = "Bruno Mars",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("573a1d7c-694e-4f66-8905-8e528f137d27"),
                            Code = 0,
                            Email = "rihanna@gmail.com",
                            IsActive = false,
                            Name = "Rihanna",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("bcb0671f-572a-4495-b5df-3f2865e081b2"),
                            Code = 0,
                            Email = "kendricklamar@gmail.com",
                            IsActive = false,
                            Name = "Kendrick Lamar",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("f2e16642-5d10-4195-8bc6-8b9dbb9dbd5a"),
                            Code = 0,
                            Email = "billieeilish@gmail.com",
                            IsActive = false,
                            Name = "Billie Eilish",
                            Password = "1111"
                        },
                        new
                        {
                            Id = new Guid("81d19ab4-52a1-4e47-9766-2c7b682e89b3"),
                            Code = 0,
                            Email = "justinbieber@gmail.com",
                            IsActive = false,
                            Name = "Justin Bieber",
                            Password = "1111"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Artists.ArtistAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ArtistAlbums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30965a2d-b2eb-448b-bedb-56e56215f76f"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f")
                        },
                        new
                        {
                            Id = new Guid("86e9eb76-1f31-40b1-a655-6b7d6860a7bd"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42")
                        },
                        new
                        {
                            Id = new Guid("87cb0a2e-63f3-491c-b164-eac43dd743f4"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            ArtistId = new Guid("c9c8d64c-fa56-4e2e-b8ef-6e41d00735e1")
                        },
                        new
                        {
                            Id = new Guid("994a42cd-1c68-4fdb-b2b1-f0e9f4ee44a5"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            ArtistId = new Guid("90ac1df8-837d-42af-a40a-a0cbd28770fd")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Artists.ArtistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("ArtistTracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("034fe159-32db-4875-9131-6426134d2743"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("8366834f-0278-46e2-8142-011813bda329")
                        },
                        new
                        {
                            Id = new Guid("062c2665-7591-4c78-82da-da9fe95f2277"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("533b7e3d-9cfd-4731-8dda-a1d5a86ff80a")
                        },
                        new
                        {
                            Id = new Guid("1227371f-f8cb-409c-ae62-9a864ce52d62"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("1afe4a9e-7121-4b34-89a6-8db6e0b6ddad")
                        },
                        new
                        {
                            Id = new Guid("1d7ace2e-de9c-492a-b535-723fb24975cb"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("f0c1326b-0646-46f4-966f-c10caa9c931b")
                        },
                        new
                        {
                            Id = new Guid("38d003fd-762e-410b-b93c-3b4ef2ec39ca"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("492f70ab-f1de-4de4-93b3-8602df66b05a")
                        },
                        new
                        {
                            Id = new Guid("960c53c2-d34a-4692-9f2b-6d6fd1015868"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("baace2ca-c2c0-4cee-b129-53079d696059")
                        },
                        new
                        {
                            Id = new Guid("983414b0-1371-4327-bd66-684afc8e3d05"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("84d5050b-a7b7-4c23-a2d1-93281183264a")
                        },
                        new
                        {
                            Id = new Guid("d033186f-8ab5-435e-9874-5238e141b148"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("6d342342-ea26-40f4-aa92-420f3a943603")
                        },
                        new
                        {
                            Id = new Guid("dc4036b5-d7ef-4788-8b33-e21b42374005"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("8e22b0a3-063e-40ae-976e-5b06f762c8ce")
                        },
                        new
                        {
                            Id = new Guid("dc96bf29-f981-4cfe-9777-a459d0ab69db"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("77b75ed9-e6d2-4d47-84c9-58af10e455c1")
                        },
                        new
                        {
                            Id = new Guid("de175c65-a3a6-4204-a1b2-318abe039cee"),
                            ArtistId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            TrackId = new Guid("7fdfa190-66d6-43be-b2af-dbbd45052828")
                        },
                        new
                        {
                            Id = new Guid("8fa88919-15b7-4fa2-a014-117a5e979ea2"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("262342b2-861e-4802-a54c-c84522188cd7")
                        },
                        new
                        {
                            Id = new Guid("f8b9412d-9784-45f3-ad10-5b84d4014ab3"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("3fde47fd-c654-4124-bc46-88d3b9bfa4df")
                        },
                        new
                        {
                            Id = new Guid("97c79ba6-febc-4d53-9e2a-1c6fdb4f3a5a"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("6c9645b5-3f50-4a11-8be0-314a97c27eb8")
                        },
                        new
                        {
                            Id = new Guid("0caf3d40-756b-46ff-8a45-3161a85a0872"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("f0a91ef7-1eaa-40d0-8273-0401bea48b5c")
                        },
                        new
                        {
                            Id = new Guid("5de801cc-0029-4706-b03f-763f1868c228"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("8842e1a3-18e2-4aa7-8b66-55150248a33a")
                        },
                        new
                        {
                            Id = new Guid("970afdc7-7e88-4d7b-8bd8-73e2a4c86f25"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("2d75a3c6-1e6b-4740-afaa-60e33bcb77e3")
                        },
                        new
                        {
                            Id = new Guid("ee34d371-d538-43a4-bd59-19f5faf67985"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("5d146662-869d-477f-8f99-620ad1f3c1d1")
                        },
                        new
                        {
                            Id = new Guid("0698c4b9-be2b-4fe9-8dbe-8c12111c6605"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("82e5f6d3-1d4a-4bc2-96d0-2d8f7852bc7e")
                        },
                        new
                        {
                            Id = new Guid("c30d6179-0407-487b-bfea-b543921d84c4"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("08d03e3d-0919-4c01-a6db-78c2abfc4d5e")
                        },
                        new
                        {
                            Id = new Guid("506ea768-1c1c-402b-9ad6-e41af208f4d7"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("e9481c7b-c007-46de-b706-4775c1d9c6de")
                        },
                        new
                        {
                            Id = new Guid("03ddc79f-b1ba-4b5b-a8fc-a40c7bf41747"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("bf9e77fd-3d3a-4a77-aae9-123d03b9a2e4")
                        },
                        new
                        {
                            Id = new Guid("6f2fc58d-1415-460b-b31f-b774d87425f3"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("6b24c35d-8589-4d35-83be-dfc48f0c8a79")
                        },
                        new
                        {
                            Id = new Guid("35b257fa-ee34-45ed-ad86-8347bc585dbc"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f")
                        },
                        new
                        {
                            Id = new Guid("ab93d52a-2279-49fd-9d89-aa0770931ae4"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("a633f860-97ce-4d9a-9960-2091db4aee78")
                        },
                        new
                        {
                            Id = new Guid("c70bbcef-922f-44bc-b716-c07118510321"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("d982cc75-bcfc-4c66-8dd6-23b1e87866e5")
                        },
                        new
                        {
                            Id = new Guid("8aac4072-4ba8-4be3-95d8-193392e1591f"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("d1c9e7c7-ee5e-4ae7-8d5e-bdb94e10bcb9")
                        },
                        new
                        {
                            Id = new Guid("79ed1f18-35ad-46e4-9d02-ab8b118b3fe3"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("4d60248e-d3f1-43e0-978f-356947c53e15")
                        },
                        new
                        {
                            Id = new Guid("fea2789f-a50e-4274-8824-534a75491e98"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("ddaa72b5-3a20-46d7-8c48-c6c7c9ea2564")
                        },
                        new
                        {
                            Id = new Guid("2b189dd4-a8c3-4921-a361-f63c37eabb70"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("997f8ae9-cc5d-4b19-9dd7-0f1d287106e9")
                        },
                        new
                        {
                            Id = new Guid("83dd7c9d-630c-4a41-ba9d-fcfdf526a299"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("5e8eae8c-7d72-4dc0-9832-6ae82f5a42ed")
                        },
                        new
                        {
                            Id = new Guid("c543cb27-3040-4e6e-b420-ab34ac4cc925"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("15dc8b5e-f87e-4ee6-8f0b-6c1f1e2f5eb1")
                        },
                        new
                        {
                            Id = new Guid("dae6391e-f96b-4807-86e8-94067b686ad2"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("c138c0a3-0dbd-4b9c-9533-d860bb4d1364")
                        },
                        new
                        {
                            Id = new Guid("ee325bd5-8b52-4c7d-8afe-5d19361e6b3b"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("f89c0c4d-59e4-4b9a-b95f-8c6d2fb4208b")
                        },
                        new
                        {
                            Id = new Guid("1d76e33d-4885-4785-b1ff-75c8593834a4"),
                            ArtistId = new Guid("8c22ffaa-6cb7-43c9-8f7f-4a204663df42"),
                            TrackId = new Guid("e43d89cd-398d-4dbb-99e6-789869f891f3")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Genres.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae14797c-31cd-432a-b2de-b3db95a82ab4"),
                            Code = 0,
                            IsActive = false,
                            Name = "Трэп"
                        },
                        new
                        {
                            Id = new Guid("8745e56f-b335-43fe-bd10-bad6bead0892"),
                            Code = 0,
                            IsActive = false,
                            Name = "Хип-Хоп"
                        },
                        new
                        {
                            Id = new Guid("baa56e06-9672-4118-aee3-4098cec4581e"),
                            Code = 0,
                            IsActive = false,
                            Name = "Эмо"
                        },
                        new
                        {
                            Id = new Guid("2f044c88-a983-4cf5-bcc1-a5d7764507ed"),
                            Code = 0,
                            IsActive = false,
                            Name = "Клауд-рэп"
                        },
                        new
                        {
                            Id = new Guid("e2a8929f-2190-4329-bae1-83b170a3677f"),
                            Code = 0,
                            IsActive = false,
                            Name = "Альтернативный рок"
                        },
                        new
                        {
                            Id = new Guid("ac38a647-9bc3-4a14-ae64-8c50964e307d"),
                            Code = 0,
                            IsActive = false,
                            Name = "Поп"
                        },
                        new
                        {
                            Id = new Guid("da7a689b-5b29-4c88-91ad-b543ce614e12"),
                            Code = 0,
                            IsActive = false,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = new Guid("d35e2479-8214-41f2-b6d6-59b892602f16"),
                            Code = 0,
                            IsActive = false,
                            Name = "Ритм-н-блюз"
                        },
                        new
                        {
                            Id = new Guid("8ff3eaba-b2c6-4a1b-96c9-0f611d17e8c6"),
                            Code = 0,
                            IsActive = false,
                            Name = "Поп-рок"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByArtistId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByArtistId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0e7bcbd-945d-453e-a9cc-e54d397a9fe9"),
                            Code = 0,
                            CreatedByArtistId = new Guid("c878736d-da07-4401-ab27-2743d4e035c5"),
                            IsActive = true,
                            IsPublic = true,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Лучшее XXXtentacion"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Playlists.PlaylistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TrackId")
                        .HasMaxLength(50)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("162609a2-ce5d-4cb7-b808-bf1acf903852"),
                            PlaylistId = new Guid("b0e7bcbd-945d-453e-a9cc-e54d397a9fe9"),
                            Position = 50.0,
                            TrackId = new Guid("8366834f-0278-46e2-8142-011813bda329")
                        },
                        new
                        {
                            Id = new Guid("2b33dd70-f22c-4186-8100-d7a2e503b454"),
                            PlaylistId = new Guid("b0e7bcbd-945d-453e-a9cc-e54d397a9fe9"),
                            Position = 100.0,
                            TrackId = new Guid("533b7e3d-9cfd-4731-8dda-a1d5a86ff80a")
                        },
                        new
                        {
                            Id = new Guid("2e8395fe-912d-499c-8a7b-5c04e47f3231"),
                            PlaylistId = new Guid("b0e7bcbd-945d-453e-a9cc-e54d397a9fe9"),
                            Position = 150.0,
                            TrackId = new Guid("1afe4a9e-7121-4b34-89a6-8db6e0b6ddad")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Tracks.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8366834f-0278-46e2-8142-011813bda329"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 1.1m,
                            IsActive = true,
                            Name = "The Explanation",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("533b7e3d-9cfd-4731-8dda-a1d5a86ff80a"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Jocelyn Flores",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("1afe4a9e-7121-4b34-89a6-8db6e0b6ddad"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Depression & Obsession",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("f0c1326b-0646-46f4-966f-c10caa9c931b"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Everybody Dies In Their Nightmares",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("492f70ab-f1de-4de4-93b3-8602df66b05a"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Revenge",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("baace2ca-c2c0-4cee-b129-53079d696059"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Save Me",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("84d5050b-a7b7-4c23-a2d1-93281183264a"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Dead Inside (Interlude)",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("6d342342-ea26-40f4-aa92-420f3a943603"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Fuck Love feat. Trippie Redd",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("8e22b0a3-063e-40ae-976e-5b06f762c8ce"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Carry On",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("77b75ed9-e6d2-4d47-84c9-58af10e455c1"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Orlando",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("7fdfa190-66d6-43be-b2af-dbbd45052828"),
                            AlbumId = new Guid("fe024194-aad4-462a-8fbd-8dd7b4a2cd90"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Ayala (Outro)",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("262342b2-861e-4802-a54c-c84522188cd7"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Teen",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3fde47fd-c654-4124-bc46-88d3b9bfa4df"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Not PLaying",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("6c9645b5-3f50-4a11-8be0-314a97c27eb8"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "JumpOutTheHouse",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("f0a91ef7-1eaa-40d0-8273-0401bea48b5c"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "New N3on",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("8842e1a3-18e2-4aa7-8b66-55150248a33a"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Slay3r",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("2d75a3c6-1e6b-4740-afaa-60e33bcb77e3"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Die4Guy",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("5d146662-869d-477f-8f99-620ad1f3c1d1"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Place",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("82e5f6d3-1d4a-4bc2-96d0-2d8f7852bc7e"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Metamorphosis",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("08d03e3d-0919-4c01-a6db-78c2abfc4d5e"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Control",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("e9481c7b-c007-46de-b706-4775c1d9c6de"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "@ MEH",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("bf9e77fd-3d3a-4a77-aae9-123d03b9a2e4"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "F33l Lik3 Dyin",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("6b24c35d-8589-4d35-83be-dfc48f0c8a79"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Over",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("9b17852c-5733-494d-8c37-ecf91fbc668f"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "King Vamp",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("a633f860-97ce-4d9a-9960-2091db4aee78"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Money And Drugs",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("d982cc75-bcfc-4c66-8dd6-23b1e87866e5"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "On That Time",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("d1c9e7c7-ee5e-4ae7-8d5e-bdb94e10bcb9"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Beno!",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("4d60248e-d3f1-43e0-978f-356947c53e15"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Vamp Anthem",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("ddaa72b5-3a20-46d7-8c48-c6c7c9ea2564"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Go2DaMoon",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("997f8ae9-cc5d-4b19-9dd7-0f1d287106e9"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "ILoveUIHateU",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("5e8eae8c-7d72-4dc0-9832-6ae82f5a42ed"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Rockstar Made",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("15dc8b5e-f87e-4ee6-8f0b-6c1f1e2f5eb1"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Punk Monk",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("c138c0a3-0dbd-4b9c-9533-d860bb4d1364"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Sky",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("f89c0c4d-59e4-4b9a-b95f-8c6d2fb4208b"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Stop Breathing",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("e43d89cd-398d-4dbb-99e6-789869f891f3"),
                            AlbumId = new Guid("c7b12644-83a9-4ccd-8418-808b11d9755e"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "New Tank",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("c878736d-da07-4401-ab27-2743d4e035c5"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Space Cadet",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("9a38a1d3-91c6-4f0e-b5b9-7d9b542cdd15"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "I Know",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("a3fe58cc-ba59-4e09-96a1-4f9e8f77f99b"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Flex Up",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("1e4b79fc-4f83-44d2-95c4-35b69f62c3ab"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Hittin My Shoulder",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("b36a20bc-04a1-4c9c-8a07-5270d1526c7e"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Cigarette",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3d8e0d8f-8b9a-4f54-9e13-3a9d7db4ce41"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "For Fun",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3e4d4f4d-46f5-4716-9b8b-c355e66b8832"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Believe Me",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("d48b865a-10ef-4f6e-aae9-58ef614fc16f"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Issa Hit",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("190e4a84-462b-4a3e-90e4-9e25a826c4d3"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Glock in My Purse",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("0e53296d-4f08-4a15-ae64-23a8f4e8d804"),
                            AlbumId = new Guid("62e05eec-dfed-462d-abfe-7489534fad8b"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "Final Fantasy",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("674a432f-3fd4-4b33-af25-82607c96a3f0"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 1.11m,
                            IsActive = true,
                            Name = "Intro",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("b68c8431-5b79-4492-9f60-9f977fd471d7"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 3.10m,
                            IsActive = true,
                            Name = "Switching Lanes (feat. Playboi Carti)",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("066d0b1d-b7c6-40b6-a48c-1f7b83084760"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 5.13m,
                            IsActive = true,
                            Name = "HULU",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("f840d9d0-7ecf-4b7c-b4e6-50118a1f6712"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 4.24m,
                            IsActive = true,
                            Name = "Couch",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("41b26f20-69e4-43d2-8db4-76ed6a5028b3"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 3.07m,
                            IsActive = true,
                            Name = "42",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("bea11ee9-0d72-4d56-b27c-33095a0787a7"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 3.08m,
                            IsActive = true,
                            Name = "Biology 101",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("8b9df2a6-df2f-4c52-83d3-03aeb745e3e3"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 4.19m,
                            IsActive = true,
                            Name = "YNS",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("61458d69-7f4a-406d-80e3-7ff0d65e7f5f"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 3.47m,
                            IsActive = true,
                            Name = "Sossboy 2 (feat. Lil Uzi Vert)",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("4fca4e84-f34c-4b73-8a66-3d1566763a8a"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 4.33m,
                            IsActive = true,
                            Name = "Practice",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("7541417e-d9db-45c5-95f3-146b6f43f523"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 4.27m,
                            IsActive = true,
                            Name = "40 Clip",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("96b13d9a-3a2d-4a61-9616-6f2f2a2e0de4"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 4.51m,
                            IsActive = true,
                            Name = "Retroville",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("6a4b25d6-ae03-4aee-a442-af50945f1aee"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 5.00m,
                            IsActive = true,
                            Name = "Drunk And Nasty (feat. Sharc)",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("0a41a3fe-6f5d-4d23-9a34-34a11b5b438b"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 2.59m,
                            IsActive = true,
                            Name = "Amen",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3f3ef649-9e39-4bda-85e5-3d763f01c31e"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 3.12m,
                            IsActive = true,
                            Name = "Groceries",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("b8fd88fb-647e-4130-83ed-801a9abf5e75"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 3.15m,
                            IsActive = true,
                            Name = "Butterfly",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("2fb86013-0a56-4f2a-bd99-3fd4f4c1f1f3"),
                            AlbumId = new Guid("f7c43f96-79e4-4244-b21b-8ac476e54495"),
                            Code = 0,
                            Duration = 0m,
                            IsActive = true,
                            Name = "4U",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("88f77e10-02c2-4182-a5e6-8946a84688a9"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 2.16m,
                            IsActive = true,
                            Name = "Survival",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("ed7f120f-0c7d-4bcf-a733-2b4de2a50b1b"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.58m,
                            IsActive = true,
                            Name = "Nonstop",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3cb2c0a8-1e79-4d6a-9b61-0af74c533787"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.04m,
                            IsActive = true,
                            Name = "Elevate",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("f52e7de3-46d6-40cc-9e67-3d28b1dd84d9"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 5.02m,
                            IsActive = true,
                            Name = "Emotionless",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("1e41186e-c7b1-40ed-85c9-4e4c5b5c33b7"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.19m,
                            IsActive = true,
                            Name = "God's Plan",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("0a0e4f09-16b3-44d2-a545-c3f23a6bda9e"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.34m,
                            IsActive = true,
                            Name = "I'm Upset",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("450cb1e3-ebc1-4dcb-a5a6-3e5e5db174d8"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.15m,
                            IsActive = true,
                            Name = "8 Out of 10",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3a1a5599-ee9e-4786-88ea-57a0edf6e977"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.25m,
                            IsActive = true,
                            Name = "Mob Ties",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("ad85a600-f97a-42f0-a951-40b9a4b3c993"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 2.43m,
                            IsActive = true,
                            Name = "Can't Take a Joke",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("64955a7c-30be-4c85-8d85-d36d487ed3d5"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.36m,
                            IsActive = true,
                            Name = "Sandra's Rose",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("b75197d8-5d56-4b1d-8a5c-1a2c8c7b73d0"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.15m,
                            IsActive = true,
                            Name = "Talk Up",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("e1e8b1f7-0a07-428e-bc1d-c08dbd5c6744"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.46m,
                            IsActive = true,
                            Name = "Is There More",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("2a4b28e2-7a44-4716-8247-3b03d75e27d9"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.26m,
                            IsActive = true,
                            Name = "Peak",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("8fb522a4-80c7-4551-95e9-29b4282dc81a"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 4.07m,
                            IsActive = true,
                            Name = "Summer Games",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("d65a624a-c81b-4ed1-af0a-8b27ac872e6e"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 4.22m,
                            IsActive = true,
                            Name = "Jaded",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("f0d98d33-4c4f-4d87-9a5f-33fe7c1ab7a2"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.30m,
                            IsActive = true,
                            Name = "Nice for What",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("3bc4e4a4-1b6f-4a53-89fc-6e62fdd442a9"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.02m,
                            IsActive = true,
                            Name = "Finesse",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("c0e4e1d2-0c43-41f1-952f-788496ab6f8f"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.27m,
                            IsActive = true,
                            Name = "Ratchet Happy Birthday",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("55e55f39-af4d-4d45-8e9a-8e5b9daaf2e4"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 2.37m,
                            IsActive = true,
                            Name = "That's How You Feel",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("a0c7644a-73b7-4b3a-b457-7e51e1f63a17"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 2.42m,
                            IsActive = true,
                            Name = "Blue Tint",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("71d0a71f-9e5e-4fbf-8be5-0b39a10781f2"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.37m,
                            IsActive = true,
                            Name = "In My Feelings",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("2e8f13db-8b78-4ff1-ba08-2e47abf35127"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 4.05m,
                            IsActive = true,
                            Name = "Don't Matter to Me",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("52a3a0db-7172-41a6-8a60-6e2533f3e5b0"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 4.49m,
                            IsActive = true,
                            Name = "After Dark",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("a0fc64ff-fa2b-4d7d-9650-3a083ebdca24"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 3.39m,
                            IsActive = true,
                            Name = "Final Fantasy",
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("d8b23e3c-f1d1-47be-82b6-77a4c5e67f35"),
                            AlbumId = new Guid("bc5b6b69-c641-4105-a906-19b88dbbb4ae"),
                            Code = 0,
                            Duration = 5.09m,
                            IsActive = true,
                            Name = "March 14",
                            Number = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Albums.AlbumGenre", b =>
                {
                    b.HasOne("Domain.Entities.Albums.Album", "Album")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Genres.Genre", "Genre")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Domain.Entities.Artists.ArtistAlbum", b =>
                {
                    b.HasOne("Domain.Entities.Albums.Album", "Album")
                        .WithMany("ArtistAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Artists.Artist", "Artist")
                        .WithMany("ArtistAlbums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Entities.Artists.ArtistTrack", b =>
                {
                    b.HasOne("Domain.Entities.Artists.Artist", "Artist")
                        .WithMany("ArtistTracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tracks.Track", "Track")
                        .WithMany("ArtistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Domain.Entities.Genres.Genre", b =>
                {
                    b.HasOne("Domain.Entities.Albums.Album", null)
                        .WithMany("Genres")
                        .HasForeignKey("AlbumId");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.Playlist", b =>
                {
                    b.HasOne("Domain.Entities.Artists.Artist", "CreatedByArtist")
                        .WithMany("Playlists")
                        .HasForeignKey("CreatedByArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByArtist");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.PlaylistTrack", b =>
                {
                    b.HasOne("Domain.Entities.Playlists.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tracks.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.HasOne("Domain.Entities.Artists.Artist", "Artist")
                        .WithMany("Sessions")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Entities.Tracks.Track", b =>
                {
                    b.HasOne("Domain.Entities.Albums.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Domain.Entities.Albums.Album", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("ArtistAlbums");

                    b.Navigation("Genres");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Domain.Entities.Artists.Artist", b =>
                {
                    b.Navigation("ArtistAlbums");

                    b.Navigation("ArtistTracks");

                    b.Navigation("Playlists");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Genres.Genre", b =>
                {
                    b.Navigation("AlbumGenres");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Domain.Entities.Tracks.Track", b =>
                {
                    b.Navigation("ArtistTracks");

                    b.Navigation("PlaylistTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
